version: '3'
services:
  app:
    build: app
    volumes:
      - ./app/main.py:/main.py
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: app.main

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:6.8.4
    expose:
      - 9200
      - 9300
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:6.8.4
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
